<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-10T11:51:25 CST" name="Default suite" finished-at="2025-02-10T11:51:29 CST" duration-ms="3859">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runner.TestRunner@d771cc9]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2025-02-10T11:51:25 CST" name="Default test" finished-at="2025-02-10T11:51:29 CST" duration-ms="3859">
      <class name="runner.TestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:runner.TestRunner@d771cc9]" started-at="2025-02-10T11:51:25 CST" name="setUpClass" finished-at="2025-02-10T11:51:25 CST" duration-ms="223" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1f57666b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runner.TestRunner@d771cc9]" started-at="2025-02-10T11:51:25 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-02-10T11:51:29 CST" duration-ms="3538" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["create user"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["create user for user api"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at apiClasses.UserApi.verifyStatusCode(UserApi.java:125)
at stepDefinition.CrudStepDefinition.user_gets_valid_response_body_for_all(CrudStepDefinition.java:32)
at âœ½.user gets valid response body for all(file:///C:/Users/sridh/Desktop/vidhya/API/api_boot/src/test/resources/feature/crudfile.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:runner.TestRunner@d771cc9]" started-at="2025-02-10T11:51:29 CST" name="tearDownClass" finished-at="2025-02-10T11:51:29 CST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runner.TestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
